export const DASHBOARD_DEFAULT_PORT = '24576';
export const DASHBOARD_FALLBACK_PORT_START = 24577;
export const DASHBOARD_FALLBACK_PORT_END = 24590;
export const DASHBOARD_PREVIEW_PORT_FROM = 24602;
export const DASHBOARD_PREVIEW_PORT_UNASSIGNED_TO = 24665;

export const MANAGED_INSTANCE_HOST = '127.0.0.1';
export const MANAGED_INSTANCE_PORT_FROM = 3457;
export const MANAGED_INSTANCE_PORT_COUNT = 50;
export const MANAGED_INSTANCE_PORT_TO =
    MANAGED_INSTANCE_PORT_FROM + MANAGED_INSTANCE_PORT_COUNT - 1;

export const DASHBOARD_SCAN_TIMEOUT_MS = 450;
